// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd7GuCqVGGMzae5ilTwQFReBlwPqjPa6g',
    appId: '1:653091558823:web:7481ba2e7c84bd7c5e5282',
    messagingSenderId: '653091558823',
    projectId: 'chatapp-41e14',
    authDomain: 'chatapp-41e14.firebaseapp.com',
    storageBucket: 'chatapp-41e14.appspot.com',
    measurementId: 'G-HMBW7PM2F4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7H2uhY3ws3r8O9nYYPldcPut0wohU4_A',
    appId: '1:653091558823:android:fab227982b7081715e5282',
    messagingSenderId: '653091558823',
    projectId: 'chatapp-41e14',
    storageBucket: 'chatapp-41e14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZQCRo1Eu6Wj86kY29eZN7DOKg5IxXnJo',
    appId: '1:653091558823:ios:5d410f257c4b8e115e5282',
    messagingSenderId: '653091558823',
    projectId: 'chatapp-41e14',
    storageBucket: 'chatapp-41e14.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZQCRo1Eu6Wj86kY29eZN7DOKg5IxXnJo',
    appId: '1:653091558823:ios:5d410f257c4b8e115e5282',
    messagingSenderId: '653091558823',
    projectId: 'chatapp-41e14',
    storageBucket: 'chatapp-41e14.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd7GuCqVGGMzae5ilTwQFReBlwPqjPa6g',
    appId: '1:653091558823:web:42993db4dbed7f285e5282',
    messagingSenderId: '653091558823',
    projectId: 'chatapp-41e14',
    authDomain: 'chatapp-41e14.firebaseapp.com',
    storageBucket: 'chatapp-41e14.appspot.com',
    measurementId: 'G-ZCMVLY5EQV',
  );

}